### PR TITLE
relax peerDependencies.

### PR DESCRIPTION
**Pull request by chirag04**
cannot install this with react-native 0.5.0

### CODE REVIEW

**Comment by oblador** [comment]
Thanks!

**Comment by chirag04** [comment]
no problem. can you bump the version?

**Comment by oblador** [comment]
Was just about to, done!

**Comment by chirag04** [comment]
sweet. Thanks :)

Also, can you have a quick look at my last comment on this?: https://github.com/oblador/react-native-keychain/issues/3

**Comment by chirag04** [comment]
What do you think about just dropping peerDependency and having it as a dependency? 

It works with 0.5 but wont work with 0.6 now.

https://github.com/chirag04/react-native-dashed-border/blob/master/package.json#L24-L26

**Pull request merged**
