### PR TITLE
Add react-native-keychain on tvOS 

### PR DESCRIPTION
**Pull request by JulienKode**
Now we can use react native keychain on tvOS, I have test it and I use it in my project and it works perfectly

tmp

I've disable: 
- setSharedWebCredentialsForServer
- requestSharedWebCredentials

Because they are only for [iOS](https://developer.apple.com/documentation/security/shared_web_credentials)

### CODE REVIEW

**Comment by JulienKode** [comment]
@oblador any update ?

**Comment by oblador** [comment]
Sorry, just been very busy lately. Thanks for you PR though! Could you fix the indentation? Right now it's hard to review as everything shows up as changed.

**Comment by JulienKode** [comment]
@oblador sorry for my indentation, now this is fixed

**Comment by oblador** [comment]
Ace, thanks man!

**Pull request merged**
