### PR TITLE
Fix strongbox decryption data corruption

### LINKED ISSUE #208: Cannot decrypt password when length is too long on some Android devices.
Hi,

We are having an issue with decrypting a lengthy password when using a Pixel 3 and when using the latest version of react-native 0.59.4. It works on any other device we tested using this version, but not on a Pixel 3. And it works on the Pixel 3 when using react-native 0.57.1, which is currently used in your example application. We have not tried any other react-native versions. We have been able to reproduce it on the Pixel 3, but cannot assume it is only present on that device.

We have created a repo with the Keychain Example app from this repo, but have updated it to the latest react-native version. Please see the repo readme for how to use the example: https://github.com/timbjarengren/react-native-keychain-test-059

Our use case is that we save json containing accessToken and refreshToken using setGenericPassword. However, when this data is too long, a Pixel 3 won't be able to decrypt the data. Is this a valid use case?

This issue might be related, since the error message "could not decrypt bytes" is the same message we see as well:
- https://github.com/oblador/react-native-keychain/issues/177

If you need any more information, please let us know. Hopefully this can get resolved soon!

### PR DESCRIPTION
**Pull request by aeirola**
Fixes #208 by simplifying the data decryption implementation. Still not sure why the use of [CipherInputStream](https://developer.android.com/reference/javax/crypto/CipherInputStream) caused the data corruption, but this seems to fix it.

Original decryption implementation seems to be from https://github.com/oblador/react-native-keychain/commit/145a0983cbb3176ea099bee125740badcea027e7, but couldn't find any indication to why the stream based implementation was used originally.

Tested on a Pixel 3a running Android 10

### CODE REVIEW

**Comment by mandrigin** [comment]
@oblador I think it is ready to be merged. Should I do that?

**Comment by aeirola** [comment]
I was personally waiting on merging the PR until someone would react to my comment https://github.com/oblador/react-native-keychain/issues/208#issuecomment-566912009 and test the patch with some other device than a Pixel 3a. Unfortunately no-one seems to have had the time to do that yet, and given the holidays it might be that it takes a while until someone does.

Anyways, in my opinion the PR should be safe to merge and publish. And since the changes only affect decoding, any issues with the patch shouldn't cause any permanent harm.

**Comment by aeirola** [comment]
Got a couple of 3rd party confirmations about the fix working on 3a and 3 XL devices. I'd say that it is safe to merge.

What conventions are you following regarding PR merges? Author or reviewer merges?

**Comment by vonovak** [comment]
I'll merge and release this tomorrow unless anyone else does that before me (feel free to do so) :)

**Pull request merged**
