### PR TITLE
Remove tryGenerateStrongBoxSecurityKey on generateKeyAndStoreUnderAlias

### LINKED ISSUE #208: Cannot decrypt password when length is too long on some Android devices.
Hi,

We are having an issue with decrypting a lengthy password when using a Pixel 3 and when using the latest version of react-native 0.59.4. It works on any other device we tested using this version, but not on a Pixel 3. And it works on the Pixel 3 when using react-native 0.57.1, which is currently used in your example application. We have not tried any other react-native versions. We have been able to reproduce it on the Pixel 3, but cannot assume it is only present on that device.

We have created a repo with the Keychain Example app from this repo, but have updated it to the latest react-native version. Please see the repo readme for how to use the example: https://github.com/timbjarengren/react-native-keychain-test-059

Our use case is that we save json containing accessToken and refreshToken using setGenericPassword. However, when this data is too long, a Pixel 3 won't be able to decrypt the data. Is this a valid use case?

This issue might be related, since the error message "could not decrypt bytes" is the same message we see as well:
- https://github.com/oblador/react-native-keychain/issues/177

If you need any more information, please let us know. Hopefully this can get resolved soon!

### PR DESCRIPTION
**Pull request by BernabeFelix**
Fixes #208 

Remove tryGenerateStrongBoxSecurityKey while there's a better fix like adding an option for this function

### CODE REVIEW

**Comment by fjcaetano** [comment]
Why was this pull-request reverted? This commit fixed an issue we're facing with Pixel 3 caused by StrongBox

**Comment by rodrigofeijao** [comment]
@oblador Do you know anything about this being reverted?

**Comment by rodrigofeijao** [comment]
@vonovak Do you have any idea why this have been reverted?

**Comment by vonovak** [comment]
@rodrigofeijao no, I don't. Unfortunately, I don't have any background on this feature.

**Comment by rodrigofeijao** [comment]
@vonovak This is causing problems on people storing big keys on Pixel devices (including the brand new Pixel4). Multiple users has tried it and it solves the problem. Should I create a MR to put this back? 

Think a better approach than this would be having a flag to make this StrongBox optional if the developer want it, something like: 

```
await Keychain.setGenericPassword(username, password, {useStrongBox: false})
```

**Comment by echolocation** [comment]
Looks like in #208 they decided to revert the commit because the fix was just disabling StrongBox rather than solving the core issue: https://github.com/oblador/react-native-keychain/issues/208#issuecomment-529139395

I agree with @rodrigofeijao  though, that the changes would be useful to have in the package in the mean time, optimally with a parameter that controls it as stated above.

**Comment by vonovak** [comment]
@rodrigofeijao yes, the proposed solution sounds good, would you open a PR for this? Thank you.

**Comment by rodrigofeijao** [comment]
@vonovak PR created [here](https://github.com/oblador/react-native-keychain/pull/281)

**Pull request merged**
