### PR TITLE
Conditionally include Android Gradle plugin

### PR DESCRIPTION
**Pull request by friederbluemle**
This also removes the now obsolete Gradle wrapper from the root folder.

One initial commit with updates to `.npmignore` and `.gitignore` ensures that _only_ required files will be part of the published artifact.

Note: I did _not_ touch the *target SDK level* - It is still set to `26` and will need to be addressed in a separate PR.

### CODE REVIEW

**Comment by friederbluemle** [comment]
@oblador @vonovak - Please take a quick look at this if you have a moment. Thanks!

**Comment by vonovak** [comment]
@friederbluemle hi and thanks you for the PR. 

Can you please expand on the motivation of doing this? What is the benefit? Is there some problem with the current setup? Is this a breaking change? - It looks fine to me, I just need a little more context for this.

> obsolete Gradle wrapper

is it obsolete because of the changes made or has it been deprecated (do you have a docs link for this deprecation)?

> I did not touch the target SDK level - It is still set to 26 and will need to be addressed in a separate PR.

why does it have to be changed? :D

Sorry for a bunch of dumb questions, I'm just trying to understand the context more. Thanks.

**Comment by friederbluemle** [comment]
Hi @vonovak - Sure thing, let me expand:

The original reason these files were moved into the root of the project was to avoid potential conflicts and additional downloads on Android when using a different version of the Android Gradle plugin.

Some more background info here: https://github.com/react-native-community/discussions-and-proposals/issues/151

A simpler solution was found that lets us keep everything in place (i.e. _not_ moving Android-specific files into the root of a React Native library project). It has been adopted and merged into several other projects, for example:

- https://github.com/react-native-community/react-native-linear-gradient
- https://github.com/react-native-community/async-storage
- https://github.com/react-native-community/react-native-svg
- https://github.com/react-native-community/react-native-device-info

It is _not_ a breaking change.

Regarding the target SDK level: Android will apply compatibility measures if the target SDK level is lower than the SDK that's running on the device/emulator. It's best to avoid that and solve the task in the native way for that SDK level. In addition, at some point in the future, Google might decide to cut support these lower SDK levels (for example requiring a min level for uploads to Google Play). Therefore it's best to always try to keep these levels aligned, for a maximum compatibility and best chance of the library working with the version of React Native that it's tested against. However, increasing the target SDK level might also involve code changes. I'm just pointing it out that it will need to be addressed at some point (not super urgent, and definitely not as part of this PR).

Hope that helps. Let me know if you have any other questions.

Also rebased the branch onto the latest `master` branch.

**Comment by SaeedZhiany** [comment]
@vonovak @oblador

can you also merge this in the next release? I mean with v4.0.3?

**Pull request merged**
