### PR TITLE
[Fix] [Android] Android devices pass through biometric authentication even with passcode on unlock (Issue #518)

### PR DESCRIPTION
**Pull request by nicolas-meilan**
- Always Ask access permissions on decrypt method instead of waiting an error.
- setUserAuthenticationValidityDurationSeconds is deprecated on API 30.

### CODE REVIEW

**Review by araratispiroglu — APPROVED** [review]

**Comment by hraschan** [comment]
Would also fix #593

**Comment by alexborton** [comment]
Any movement on this issue as we are experiencing it too. Would be nice to have the fix implemented out the box

**Comment by araratispiroglu** [comment]
I've had a similar issue with this library. For me, this was happening when the app was in the foreground and the phone was locked, unlocking the phone was allowing access to the keychain item without secondary biometric verification from the app context. Currently, I'm automatically patching the file after the node modules installation. Adding `.setUserAuthenticationParameters(5, (int) KeyProperties.AUTH_BIOMETRIC_STRONG)` helps me to solve the bug.

**Review by ilyassio — APPROVED** [review]

**Comment by lewie9021** [comment]
It worth noting [`.setUserAuthenticationParameters`](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationParameters(int,%20int)) was added in API 30 (Android 11). This will mean increasing the minimum supported version of the library. A more progressive approach might be to assert the version as we build the spec:

```java
final int validityDuration = 5;
final KeyGenParameterSpec.Builder keyGenParameterSpecBuilder = new KeyGenParameterSpec.Builder(alias, purposes)
  .setBlockModes(BLOCK_MODE_ECB)
  .setEncryptionPaddings(PADDING_PKCS1)
  .setRandomizedEncryptionRequired(true)
  .setUserAuthenticationRequired(true)
  .setKeySize(keySize);

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
  keyGenParameterSpecBuilder.setUserAuthenticationParameters(validityDuration, KeyProperties.AUTH_BIOMETRIC_STRONG);
} else {
  keyGenParameterSpecBuilder.setUserAuthenticationValidityDurationSeconds(validityDuration);
}

return keyGenParameterSpecBuilder;
```

**Comment by alemarra89** [comment]
Hi all, can I ask you why default validityDuration is 5?
I notice that KeyProperties.AUTH_BIOMETRIC_STRONG value is 2, as documented here:
https://developer.android.com/reference/android/security/keystore/KeyProperties#AUTH_BIOMETRIC_STRONG

**Comment by lewie9021** [comment]
I believe historically this has been lower than 5 seconds but there's been issues with older devices where they simply aren't fast enough to decrypt the data so methods like `getGenericPassword` fail every time

**Comment by lewie9021** [comment]
The value you're referring to is simply the enum's underlying constant value. It's not that it sets it to 2 seconds from what I understand. That is handled when building the `KeyGenParameterSpec` via methods such as `setUserAuthenticationParameters` and `setUserAuthenticationValidityDurationSeconds`

**Comment by AntoineThibi** [comment]
I have used your solution @lewie9021 to keep compatibility with Android SDK < 30. It works great !
For SDK < 30, I just disable the option to access biometry for 5 seconds after coming back to the app. It's not great but I guess there are no real way to insure that the biometry is used to unlock the keystore on those version...

**Comment by P0labrD** [comment]
🆙 @oblador is there a reason not to approve and merge these changes? 🙂

**Pull request closed without merging**
