### PR TITLE
Added the ability to store a key, value pair of strings.

### PR DESCRIPTION
**Pull request by mpretty-cyro**
There are probably better naming conventions for this, but I needed the change internally so I figured I may as well send through the pull request in case someone found it useful.

### CODE REVIEW

**Comment by oblador** [comment]
Hi, thanks for your PR (and sorry about the very long review time)! You've changed indentation of the whole ObjC file, could you keep existing plz? :-)

**Comment by mpretty-homepass** [comment]
@oblador Sorry about the delay, work is pretty crazy right now. And sorry about the indentation, my IDE enforced standard XCode formatting, I usually catch it when doing a PR but must have missed it in this case. Have changed it back to 2 space indentation.

**Comment by rops** [comment]
Any chance of getting this in?
Thanks guys

**Comment by oblador** [comment]
@vonovak: If I merge this would you be down for creating the Android version of this API?

**Comment by vonovak** [comment]
@mpretty-homepass or @oblador so the benefit of this is that now if you want to save a lot of key-value pairs you need to serialize those as a json and then load it, and with this you could avoid loading the whole json and pick the key directly? Is that it?

**Comment by mpretty-homepass** [comment]
@vonovak you absolutely could do that here; you could even just do the set/get generic password methods and use them for storing key/value pairs.

The main reason I added this was to use a consistent (and self-explanatory) method internally for our app - (future junior devs might get confused if we were storing passwords on iOS and key/value pairs on Android).

Aside from that the main other differences are:
1 - the set method does an upsert (whereas the generic password one will fail if it's already set).
2 - The 'service' that the data gets stored against is a static string rather than passing it through every time (though I can't remember if we are using this anymore).

And while yes you could store a JSON blob with all of the data, that would mean someone just needs to dump the memory once to get all of the data instead of every time a secure value is accessed (not really much of an argument though).

**Comment by vonovak** [comment]
@oblador yes, I could implement same methods in java, and as I see it they would again be resolved as calls to the existing methods. So a more intuitive name for the same functionality, if I understood that correctly. @mpretty-homepass is both the key and value encrypted?
It would be then beneficial to add some unit tests to ensure both platforms behave the same (the mentioned upsert and etc. I would add that on my todo list)

**Comment by vonovak** [comment]
I'm closing this since it's unlikely to get merged now and I want to clean up the old PRs a little bit. Thank you!

**Pull request closed without merging**
