### PR TITLE
[android] return false instead of exception when entry not present

### PR DESCRIPTION
**Pull request by vonovak**
this will make it behave same as on ios

### CODE REVIEW

**Comment by oblador** [comment]
👍

**Comment by oblador** [comment]
Released in [1.2.0](https://github.com/oblador/react-native-keychain/releases/tag/v1.2.0).

**Comment by StefanWallin** [comment]
If I read the objective C-code correctly at 0.3.2, this should be clearly listed as a breaking change in the 1.0.0 release. 

Being #not_an_obj_c_master it took me quite a while to track this down. (We relied on the catch-clause for key without value to look for another key)

**Comment by vojtechnovak** [comment]
This pr was a bug fix and only concerns Android, the ios functionality was not modified.

**Comment by StefanWallin** [comment]
@vojtechnovak totally correct. But the iOS functionality changed with the 1.0.0 release and this is the only place I've found that talks about this change that I've found.

**Pull request merged**
