### PR TITLE
Android support

### PR DESCRIPTION
**Pull request by vonovak**
#12 
This build upon work of corymsmith. The difference is that I am storing the credentials encoded as base64 which is more robust. I also used a newer version of conceal library and added some debuging/error messages for logcat.

there is still some work to do on making the error reporting on the js side nicer, but this is something to start with

### CODE REVIEW

**Comment by oblador** [comment]
This is exciting! Any reason why the JS part can't be shared between platforms?

**Comment by vonovak** [comment]
are you talking about implementing the `*internetPassword` methods or the changes I did to the `convertError` method?
Actually, what is meant to be the difference between `genericPassword` and `InternetCredentials`? I'm not familiar with iOS but I see you have different methods for that. What I could do in the android implementation is call the `set/getGenericPasswordForService`(in java) for both `*internetPassword` and `*genericPassword` (from js)  and the only difference would be the service parameter which would be specified for `internetPassword` and optional for `genericPassword`.

As for `convertError` I didn't get its point, I'm returning the error message from the android module. 

I noticed there are some things I could polish, just let me know the difference I asked about and I'll update the PR.

**Comment by oblador** [comment]
So the value of internet credentials is that in iOS those can be shared with the browser, so if lets say a user has logged in to your website and then gets the app, those credentials can already be filled out basically. Probably doesn't make any sense on android as it doesn't really have a keychain AFAIK. 

I'm uncertain of the reason for `convertError`, would guess that errors returned from native are not uniform. All this code was written a while ago, about a month after initial release of RN so I was kinda new to it all and it deserves a refresh for sure. That said, I'm not actively using in any of my current projects, so if you have suggestions for refactors I'm happy to test them out for you. I have upcoming projects where I'll use it so maybe it can wait until then.  

As for the JS comment, I mean that your `index.android.js` is more or less a subset copy from `index.ios.js`, so IMHO it would make more sense to unify them into `index.js` with some conditionals.

**Comment by vonovak** [comment]
I implemented the `*internetCredentials`, they will gracefully degrade to the `genericPassword` as discussed. 
The js remains in two separate files, I'd like to leave their merge up to you or someone else who has a device or emulator or I may get to do it one day. It needs to be ensured that both apis respond the same (especially in edge/error cases) and I feel like this could get time consuming without having direct access to an ios device, while someone with it will get it working quickly.

**Comment by codyhazelwood** [comment]
@vonovak Just added a pull request to your fork merging the indexes.  I installed in my app and did some basic testing, and it seemed to work fine for me.  Basically, I used `index.ios.js` and switched based on the platform for the `convertError`, since that appeared to be the only difference besides code style.

**Comment by vonovak** [comment]
@oblador hi there, @codyhazelwood merged the index files into one `index.js` so this should now be ready for merge

**Comment by oblador** [comment]
Awesome, thanks for the team effort 👏 👍 

I'm good to merge but can't get the squash commits button to work. Could you squash them for me and it's an instamerge?

**Comment by vonovak** [comment]
@oblador this involved a forced push (is there any nicer way to do this?) but looks good to me.

**Comment by oblador** [comment]
Fantastic, thanks!

**Comment by codyhazelwood** [comment]
I think the squash is usually meant for one person doing work in a branch.  It probably didn't allow you to squash since the pull request from @vonovak had another pull request merged into it with commits from me, and there's no way to squash everything into one commit while keeping blame information from multiple collaborators.

**Pull request merged**
