### PR TITLE
Android AES GCM support via preferedCipher option

### PR DESCRIPTION
**Pull request by Skvuddudutt**
by Joel's request.

### CODE REVIEW

**Comment by pcoltau** [comment]
I'll review this, but I would like to wait until the "cleaning" is done.

**Comment by oblador** [comment]
@pcoltau Unfortunately, this as @Skvuddudutt's last assignment before his contract ended, so wouldn't assume it will be done. Can maybe help with cleaning up some of it later, but would be good if you could glance at the general approach first and see if you think it's worth continuing working on.

**Comment by pcoltau** [comment]
@oblador 

Fair enough - I'll give it a look as soon as time permits..

**Comment by Skvuddudutt** [comment]
Yeah sorry I was unclear. I did the PR to "save" the partial work I was
doing but didnt have time to finish. It hasnt been really tested and still
contains a bunch of logging. Also I think there is an issue with read
behaviour and auto migrating IIRC. I wont be doing any more work on it.

As Joel said, you might want to just look at it and see if it is something
you want to finish or just throw it away.

**Comment by pcoltau** [comment]
My review of this is done.

As @Skvuddudutt says, we need to address some issue before we can merge this. We just need to figure out who should do that. I can't promise that I'll have the time in the near future..

**Comment by mvayngrib** [comment]
@pcoltau can you clarify what issue needs to be addressed?

**Comment by pcoltau** [comment]
> @pcoltau can you clarify what issue needs to be addressed? If it's "read
> behaviour and auto migrating IIRC," could you expand that?

I forgot to "commit" my review comments 🙄- that is done now. Let me know if you have any questions.

**Comment by dsumac** [comment]
Does anyone continue to work on this topic?

**Comment by gabrielmoncea** [comment]
I see this PR #513 is doing the same think. Maybe it's more up to date with the master?

**Comment by DorianMazur** [comment]
AES GCM will be added with #678

**Pull request closed without merging**
